services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
    profiles:
      - dev

  backend-prod:
    container_name: backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
    profiles:
      - prod

networks:
  default:
    external: true
    name: app-shared
