name: Validate Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-backend:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:7.2
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Python syntax check (flake8)
        run: |
          flake8 . backend/ --exclude=.venv,__pycache__,build,dist --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Validate Docker Compose syntax
        run: |
          docker --version
          docker compose version
          docker compose -f docker-compose.yml config
